#!/bin/bash

set -e

echo "Getting conf values"

read -p "MySQL DB password: " MYSQL_PW
echo
read -p "Fleet admin email: " FLEET_ADMIN_EMAIL
echo
read -p "Fleet admin password: " FLEET_ADMIN_PW
echo

echo "Executing DB SQL setup"

mysql -u root --execute "
	CREATE DATABASE fleet;
	ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_PW';
	CREATE USER 'fleet'@'localhost' IDENTIFIED BY '$MYSQL_PW';
	GRANT ALL PRIVILEGES ON fleet.* to 'fleet'@'localhost';
	FLUSH PRIVILEGES;"

echo "Setting hostname"

echo "127.0.0.1 fleet.ccdc.local" > /etc/hosts

echo "Generating SSL cert"

openssl req \
	-x509 \
	-newkey rsa:4096 -sha256 \
	-days 3650 \
	-nodes \
	-keyout /opt/fleet/server.key \
	-out /opt/fleet/server.cert \
	-subj "/C=US/ST=California/L=Garden Grove/O=CCDC/OU=Team/CN=fleet.ccdc.local"

echo "Creating fleet linux user"

useradd -s /sbin/nologin fleet
chown -R fleet:fleet /opt/fleet

echo "Setting Fleet DB password for Systemd"

sed -i -e "s/REPLACEME/$MYSQL_PW/g" /etc/systemd/system/fleet.service

echo "Preparing fleet db migrations"

fleet prepare db --mysql_password $MYSQL_PW

echo "Enabling fleet service"

systemctl enable --now fleet

echo "Configuring fleetctl"

fleetctl config set --address "https://fleet.ccdc.local" --tls-skip-verify

echo "Creating fleet admin user"

sleep 5
fleetctl setup --email $FLEET_ADMIN_EMAIL --name "Administrator" --password $FLEET_ADMIN_PW --org-name "CCDC Team"

echo "Logging in as fleet admin"

fleetctl login --email $FLEET_ADMIN_EMAIL --password $FLEET_ADMIN_PW

echo "Applying fleet query yamls"

for i in /usr/share/fleet/queries/*.yaml; do
	fleetctl apply -f $i
done
